name: Update profile stats

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - ".github/workflows/profile-stats.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate top languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&size_weight=0.5&count_weight=0.5&theme=transparent&hide_border=true
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@v1
        with:
          options: user=${{ github.repository_owner }}&theme=dark&hide_border=true&background=00000000&disable_animations=true&timezone=Africa/Lagos
          path: profile/streak.svg

      - name: Commit profile stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "chore: update profile stats" || exit 0
          git push
